### ISSUE TITLE
关于标签

### ISSUE THREAD

**Issue by lichacha** [junqiangchen/VNet3D#1]
麻烦请问，你的前列腺数据的01标签是怎么从raw文件里面读取出来，我只能看到原始图像，还是说我忽略了什么问题，谢谢解答

**Comment by junqiangchen** [comment]
你好，原始标签数据是Case00_segmentation.raw，原始图像数据是Case00.raw，标签数据读取后背景是0，mask值是255，你只需要把图像归一化到0-1即可。
