### ISSUE TITLE
請教影像前處理

### ISSUE THREAD

**Issue by ghost** [junqiangchen/VNet3D#10]
請問如何產生Vnet3d_patch_train目錄下的前處理後的影像?  可否分享產生前處理圖檔的代碼?

**Comment by junqiangchen** [comment]
> 請問如何產生Vnet3d_patch_train目錄下的前處理後的影像? 可否分享產生前處理圖檔的代碼?

你好，该项目归属于公司，你可以参考一下肺结节的项目里面由如何生成patch图像。
