### ISSUE TITLE
关于训练自己数据

### ISSUE THREAD

**Issue by JohnMasoner** [junqiangchen/VNet3D#12]
训练您的数据时，不会报错，想过也可以。但是当我训练自己的数据的时候，会报错ValueError: cannot reshape array of size 1 into shape (128,128,1)。我自己数据也是patch成（128，128，1）的bmp，但是仍然会报错。

**Comment by junqiangchen** [comment]
你好，你需要debug一下程序，看看加载数据部分的代码是否正确。
