### ISSUE TITLE
Different between .pd and .ckpt format model file?

### ISSUE THREAD

**Issue by EricKani** [junqiangchen/VNet3D#13]
Hi,

I am a little confused  about the pd format model files. Could you please teach me the difference between:
**modelname.pd.meta/index/data-00000-of-00001** 
and 
**modelname.ckpt.meta/index/data-00000-of-00001**
?
Thanks.

Best,

pengbol

**Comment by junqiangchen** [comment]
hello,
in the project,both format model files are same.
