### ISSUE TITLE
About Train and test data.

### ISSUE THREAD

**Issue by jizhang02** [junqiangchen/VNet3D#14]
Hello, dear Mr. @junqiangchen 
I saw your train and mask data is csv format.
However, in my case, I have dozens of 3D data which is nii.gz format.
They can convert to h5 file. But I don't know how to read it into vnet model.
And in your case, why do you use csv format?
And in csv file,  why the content is paths of images? but not 3D data?
Any way, I wonder how to read 3D data into models, could you give me some hints?
Thank you!

**Comment by junqiangchen** [comment]
you can find many tensorflow read h5 file example,in my project,the 3D data is very big,can't load all in the memory.
