### ISSUE TITLE
prepared data

### ISSUE THREAD

**Issue by Jluxcs** [junqiangchen/VNet3D#17]
Hi, Junqiang. I can't find the the prepared data on the Baidu cloud. How can i download the prepared data. Just like you writed in the readme file.

**Comment by Jluxcs** [comment]
or how can i obtain the patch data.

**Comment by junqiangchen** [comment]
hi,you can prepare patch data by yourself,pls follow the project of LiTS---Liver-Tumor-Segmentation-Challenge,you can find the getPatchImageAndMask.py file,just modify input and output path,hope it helpful.
