### ISSUE TITLE
数据集处理

### ISSUE THREAD

**Issue by 975150313** [junqiangchen/VNet3D#18]
您是不是遗漏了数据集的处理过程，2012数据集是.mhd,您这训练过程变成bmp...

**Comment by junqiangchen** [comment]
> 您是不是遗漏了数据集的处理过程，2012数据集是.mhd,您这训练过程变成bmp...

您好，
数据预处理这部份当时没有整理出来，不过其处理过程非常简单，可以参考我的其它项目内容，这里只有训练的网络实现。谢谢

**Comment by mmitach** [comment]
您好，为什么数据的predict跑不通啊，我用的就是你的训练模型和数据，谢谢
