### ISSUE TITLE
how reproduce the files .csv to train the model

### ISSUE THREAD

**Issue by DrraBL** [junqiangchen/VNet3D#19]
HI 
thank you for your great work but i wanna ask you some questions:

1: I couldn't download the trained model, can you please send me drive link or Dropbox to download
2: for the files promise12Vnet3dImage.csv and promise12Vnet3dMask.csv, as i understand that you changed the dataset to image and then save it in csv file right? so for me I need to convert promise12 to images and then create these two files or just use your files for training and convert the test data to test the model.
Please le know because i meet a lot of error and i am new in this domain.

thank you in advance

**Comment by junqiangchen** [comment]
hi,

you should write the data processing program by yourself.

thank you
