### ISSUE TITLE
关于测试数据

### ISSUE THREAD

**Issue by 491506870** [junqiangchen/VNet3D#2]
你好，请问能提供一下用于测试的数据吗？promise12官网的链接跳转到dropbox后死活下载不了了....感谢！
另外想请问一下，你是把每一堆样本都随机取了18-21个左右的patch吗？谢谢！

**Comment by lichacha** [comment]
你试出结果了吗   训练模型是128*128   predict()函数是测试256*256的    作者能提供一下256*256的测试集吗

**Comment by junqiangchen** [comment]
> 你好，请问能提供一下用于测试的数据吗？promise12官网的链接跳转到dropbox后死活下载不了了....感谢！
> 另外想请问一下，你是把每一堆样本都随机取了18-21个左右的patch吗？谢谢！
您好，我会把原始数据分享到百度云盘上去的。因为原始图像太大，3DVnet没办法在GPU上训练，所以我把图像进行了取patch操作。

**Comment by junqiangchen** [comment]
> 你试出结果了吗 训练模型是128_128 predict()函数是测试256_256的 作者能提供一下256*256的测试集吗

256*256的数据是从原始图像上取patch拿出来的，我会把原始数据分享出来，见百度云地址。
