### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by shiontao** [junqiangchen/VNet3D#3]
你好,我目前的dice很高,但是distance那两项分数非常低,能问一下这造成的原因以及解决的办法吗.

**Comment by junqiangchen** [comment]
不知道你指的distance两项具体是哪两项，dice越高说明分割结果与标准结果越接近，distance可能指的是分割结果与标准结果的差异，值越小说明差异越小。

**Comment by shiontao** [comment]
> 不知道你指的distance两项具体是哪两项，dice越高说明分割结果与标准结果越接近，distance可能指的是分割结果与标准结果的差异，值越小说明差异越小。


我目前的结果是 42nd | kakatao | 8 Nov. 2018, 我的dice都0.91了,跟前几的差不多了,但是
`
the average boundary distance, the average over the shortest distances between the boundary points of the volumes
the 95% Haussdorf distance
`
这两个指标非常差

**Comment by junqiangchen** [comment]
我看了你的结果确实有些case的分数很差，我在分析的时候没有考虑这么多指标，我只看了“total_score”这个指标，针对里面分数比较低的case，我用了3DVNet和2DVNet结合的方法去分割的。

**Comment by shiontao** [comment]
> 我看了你的结果确实有些case的分数很差，我在分析的时候没有考虑这么多指标，我只看了“total_score”这个指标，针对里面分数比较低的case，我用了3DVNet和2DVNet结合的方法去分割的。

你好,那你做了什么后处理吗

**Comment by junqiangchen** [comment]
就是分别用3DVnet和2DVnet跑出两个分割结果，然后对两个结果进行融合处理，我是用3D的结果来确定Z方向的范围，用2D的结果来确定XY平面的结果。

**Comment by qe903121** [comment]
請教一下，您說的3D的結果也是由Softmax產生出的3D mask嗎?

**Comment by junqiangchen** [comment]
> 請教一下，您說的3D的結果也是由Softmax產生出的3D mask嗎?

是的，因为二分类，我没有用softmax函数我直接用的是sigmod函数来产生3D Mask的。
