### ISSUE TITLE
关于数据集处理

### ISSUE THREAD

**Issue by luowy1001** [junqiangchen/VNet3D#7]
首先，非常感谢你们的工作！
有几个小问题想请教：
1. 原始数据的每个volume的depth不尽相同，从47到17不等，而您的patch数据集的每个batch的depth都是 
    64，请问您是具体如何处理，生成数据集的？
2.关于数据预处理：您具体采用了什么数据预处理和数据augmentation策略？
 非常感谢！
@junqiangchen

**Comment by junqiangchen** [comment]
> 首先，非常感谢你们的工作！
> 有几个小问题想请教：
> 
> 1. 原始数据的每个volume的depth不尽相同，从47到17不等，而您的patch数据集的每个batch的depth都是
>    64，请问您是具体如何处理，生成数据集的？
>    2.关于数据预处理：您具体采用了什么数据预处理和数据augmentation策略？
>    非常感谢！
>    @junqiangchen

非常感谢您提出的问题，1、我为了方便训练将所有的图像进行线性插值将图像都插值到512x512x64的大小的。2、数据预处理主要就用了直方图匹配和归一化，数据没有做augmentation策略。

**Comment by luowy1001** [comment]
> > 首先，非常感谢你们的工作！
> > 有几个小问题想请教：
> > 
> > 1. 原始数据的每个volume的depth不尽相同，从47到17不等，而您的patch数据集的每个batch的depth都是
> >    64，请问您是具体如何处理，生成数据集的？
> >    2.关于数据预处理：您具体采用了什么数据预处理和数据augmentation策略？
> >    非常感谢！
> >    @junqiangchen
> 
> 非常感谢您提出的问题，1、我为了方便训练将所有的图像进行线性插值将图像都插值到512x512x64的大小的。2、数据预处理主要就用了直方图匹配和归一化，数据没有做augmentation策略。

非常感谢您的回答，想关于插值追问几个问题：
1. 您具体使用什么插值函数？（opencv，sitk ... ... or other libs）
2. 对于训练集来说，label的插值如何处理？我想可能与对image的处理相同，那么image和label之间严格 
    的一一对应关系如何保证？
3. 对于test数据（30个volume，比赛数据，无label），我看 `vnet3d_train_predict.py` 中的 `predict0()` 函数，也将depth维度插值为64，这样的插值如何恢复到原始的depth？
再次感谢 @junqiangchen

**Comment by junqiangchen** [comment]
> > > 首先，非常感谢你们的工作！
> > > 有几个小问题想请教：
> > > 
> > > 1. 原始数据的每个volume的depth不尽相同，从47到17不等，而您的patch数据集的每个batch的depth都是
> > >    64，请问您是具体如何处理，生成数据集的？
> > >    2.关于数据预处理：您具体采用了什么数据预处理和数据augmentation策略？
> > >    非常感谢！
> > >    @junqiangchen
> > 
> > 
> > 非常感谢您提出的问题，1、我为了方便训练将所有的图像进行线性插值将图像都插值到512x512x64的大小的。2、数据预处理主要就用了直方图匹配和归一化，数据没有做augmentation策略。
> 
> 非常感谢您的回答，想关于插值追问几个问题：
> 
> 1. 您具体使用什么插值函数？（opencv，sitk ... ... or other libs）
> 2. 对于训练集来说，label的插值如何处理？我想可能与对image的处理相同，那么image和label之间严格
>    的一一对应关系如何保证？
> 3. 对于test数据（30个volume，比赛数据，无label），我看 `vnet3d_train_predict.py` 中的 `predict0()` 函数，也将depth维度插值为64，这样的插值如何恢复到原始的depth？
>    再次感谢 @junqiangchen

1、用的是sitk库去做插值。
2、插值的时候对于image和label采用不同的插值方法：image采用线性插值方法，label采用最近邻插值方法。一一对应其实不是很难，只需要对image插值完成后，再对相应的label进行插值即可，不同的只是插值方法，其他所有的大小参数都是一样的。
3、在test的时候，首先将原始image插值成512x512x64大小，再预测结束得到结果后，对预测label进行插值到原始image的大小即可。
如有问题，随时提问，谢谢。

**Comment by cz-xjtu** [comment]
您好，您说的“在test的时候，首先将原始image插值成512x512x64大小”这个怎么将原始image插值成512x512我可以理解，怎么插值成512x512x64大小呀？是随机的将原来测试集每个volume的20几张到30几张不等的图片扩充到64张吗？谢谢！

**Comment by junqiangchen** [comment]
> 您好，您说的“在test的时候，首先将原始image插值成512x512x64大小”这个怎么将原始image插值成512x512我可以理解，怎么插值成512x512x64大小呀？是随机的将原来测试集每个volume的20几张到30几张不等的图片扩充到64张吗？谢谢！

我是用simpleitk进行插值的，例如：原始512x512x35，我将图像差值到512x512x64，然后测试，将测试结果再插值成512x512x35即可。
