### ISSUE TITLE
Downloading from pan.baidu

### ISSUE THREAD

**Issue by dPacc** [junqiangchen/VNet3D#8]
Hi, downloading the data you uploaded on pan.baidu is not easy for people living outside of China, It would be great if you could share it on Google drive. If that's not possible, could you tell how to modify the .csv files according to the official PROMSE12 dataset? Is there a particular folder structure to follow? Thanks in advance

**Comment by junqiangchen** [comment]
> Hi, downloading the data you uploaded on pan.baidu is not easy for people living outside of China, It would be great if you could share it on Google drive. If that's not possible, could you tell how to modify the .csv files according to the official PROMSE12 dataset? Is there a particular folder structure to follow? Thanks in advance

It is not easy for me to share the data on Google drive.the csv file is the train data folder,first you should resample the .mhd source data to (512,512,64) image,then crop the (128,128,64)patch images by order method,and save the patch images to disk,last save every patch image to the csv file.

**Comment by dPacc** [comment]
> > Hi, downloading the data you uploaded on pan.baidu is not easy for people living outside of China, It would be great if you could share it on Google drive. If that's not possible, could you tell how to modify the .csv files according to the official PROMSE12 dataset? Is there a particular folder structure to follow? Thanks in advance
> 
> It is not easy for me to share the data on Google drive.the csv file is the train data folder,first you should resample the .mhd source data to (512,512,64) image,then crop the (128,128,64)patch images by order method,and save the patch images to disk,last save every patch image to the csv file.

Thank you for the reply, I will try this :)

**Comment by gorkemguzeler** [comment]
Hi @dPacc, @junqiangchen,

I cannot download the pre-trained model from pan.baidu.

Can you share a drive link if you already have it?

Thanks in advance.
