### ISSUE TITLE
关于代码中的epoch

### ISSUE THREAD

**Issue by HainKUL** [junqiangchen/VNet3D#9]
请问代码里问什么每个epoch只进行一次取_next_batch操作呢？理论上一个epoch是不是该走完所有的training examples？我可以该将代码里的一个epoch理解为一个iteration？

**Comment by junqiangchen** [comment]
> 请问代码里问什么每个epoch只进行一次取_next_batch操作呢？理论上一个epoch是不是该走完所有的training examples？我可以该将代码里的一个epoch理解为一个iteration？

是的，一次epoch就是一次iteration
